import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { TextField, Button } from "@mui/material"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Job Recommendation Engine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://zephyrsolutions.com">Zephyr</a>
        </h1>
        <TextField
          required
          fullWidth
          name="password"
          placeholder='Look for jobs'
          type="text"
          id="password"
          autoComplete="new-password"
          sx={{ mt: 3, mb: 2 }}
        />
        <Button 
          variant="outlined"
          sx={{ mt: 3, mb: 2 }}>
          Search
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
